# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [2]:
# The code goes here
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [107]:
#Code comes here
lst1 = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1] #create list of 10 ones
arr1 = np.array(lst1) #list into array 
print(type(lst1))
print(type(arr1))
print(arr1)

#arry of integers 1 to 20
arr2 = np.arange(1, 21, 1, dtype="int") #used range with spacing of 1
print(arr2)

#5x5 matrix of ones with dtype int 
lst3= [[1,1,1,1,1], [1,1,1,1,1,], [1,1,1,1,1,], [1,1,1,1,1], [1,1,1,1,1]] #list of 5x5 ones
lst3 = np.dtype(int)
print(arr3)

arr3a = np.ones((5,5))
print(arr3a)

<class 'list'>
<class 'numpy.ndarray'>
[1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [14]:
arr4 = np.random.rand(3,3,3)
print(arr4)
arr4b = arr4.reshape(27)
print(arr4b)

arr4 = np.ones((5,5,5,5,5))

[[[0.38752965 0.27494696 0.61504638]
  [0.78951017 0.59952171 0.48170547]
  [0.15054277 0.06333663 0.36119389]]

 [[0.36821001 0.50052422 0.08389488]
  [0.20187743 0.19193109 0.13976857]
  [0.49632859 0.11941418 0.89859474]]

 [[0.53958019 0.65812146 0.34352121]
  [0.66992866 0.29478632 0.01315899]
  [0.72043354 0.76427475 0.00301298]]]
[0.38752965 0.27494696 0.61504638 0.78951017 0.59952171 0.48170547
 0.15054277 0.06333663 0.36119389 0.36821001 0.50052422 0.08389488
 0.20187743 0.19193109 0.13976857 0.49632859 0.11941418 0.89859474
 0.53958019 0.65812146 0.34352121 0.66992866 0.29478632 0.01315899
 0.72043354 0.76427475 0.00301298]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [15]:
# Code comes here
arr5= np.linspace(1,10,20, dtype="int") #linspace and input range of 1-10 and the number of space(20)
print(arr5)


[ 1  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [22]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [17]:
20

20

In [37]:
#arr1=a
a=np.arange(1,26).reshape(5,-1)
print(a[3][4])


20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [44]:
# Code come here
a = np.arange(1,26).reshape(5,-1)
print(a[0][3:5])
print(a[1][3:5])
print(a[2][3:5])
print(a[3][3:5])
print(a[4][3:5])

[4 5]
[ 9 10]
[14 15]
[19 20]
[24 25]


```python
array([ 6,  7,  8,  9, 10])
```

In [30]:
# Code comes here
a = np.arange(1,26).reshape(5,-1)
print(a[1])

[ 6  7  8  9 10]


## 2.5 

Calculate the sum of all the numbers in `a`.

In [45]:
# Code comes here
a = np.arange(1,26).reshape(5,-1)
total = np.sum(a)
print(total)

325


## 2.6 

Calculate the sum of each row in `a`.

In [50]:
# Code comes here
a = np.arange(1,26).reshape(5,-1)
total = np.sum(a,axis=1)
print(total)

[ 15  40  65  90 115]


In [49]:
# longer version of calcuating sum of rows - above is more efficent 
a = np.arange(1,26).reshape(5,-1)
a1 = np.arange(1,6)
print(sum(a1))
a2 = np.arange(6,11)
print(sum(a2))




15
40


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [65]:
# Code comes here
a = np.arange(1,26).reshape(5,-1)
mean = np.mean(a)
print(mean)

13.0


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [4]:
# Codes comes here
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv')
print(df)


         country             food_category  consumption  co2_emmission
0      Argentina                      Pork        10.51          37.20
1      Argentina                   Poultry        38.66          41.53
2      Argentina                      Beef        55.48        1712.00
3      Argentina               Lamb & Goat         1.56          54.63
4      Argentina                      Fish         4.36           6.96
...          ...                       ...          ...            ...
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh                      Rice       171.73         219.76
1428  Bangladesh                  Soybeans         0.61           0.27
1429  Bangladesh   Nuts inc. Peanut Butter         0.72           1.27

[1430 rows x 4 columns]


## 2.10 

How many rows and columns are there in the dataframe?

In [91]:
#Code comes here
Columns = len(df.columns)
print(Columns)
Rows = len(df)
print(Rows)

4
1430


## 2.11

What is the mean `co2_emission` of the whole dataset?

In [86]:
# Code comes here
meanCo2 = df["co2_emmission"].mean()
print(meanCo2)



74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [96]:
# Code comes here
maxCo2 = df["co2_emmission"].max #without food type and country
print(maxCo2) 

df2 = df.loc[df["co2_emmission"].idxmax()] #used loc to access rows and idmax to return the index
print(df2)

<bound method NDFrame._add_numeric_operations.<locals>.max of 0         37.20
1         41.53
2       1712.00
3         54.63
4          6.96
         ...   
1425      31.21
1426       3.33
1427     219.76
1428       0.27
1429       1.27
Name: co2_emmission, Length: 1430, dtype: float64>
country          Argentina
food_category         Beef
consumption          55.48
co2_emmission       1712.0
Name: 2, dtype: object


## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [12]:
#code comes here


Co2df = df.loc[df["co2_emmission"] > 1000] #loc for rows. countires > 1000kg emmission
print(len(Co2df))



5


## 2.14

Which country consumes the least amount of beef per person per year?


In [31]:
# Code comes here
beefdf = df.loc[df["food_category"] == "Beef"] #created a dataframe for beef using loc
minbeef=beefdf.loc[beefdf["consumption"]==beefdf.consumption.min()] #minimum value of beefdf
print(minbeef.country)
   

1410    Liberia
Name: country, dtype: object


## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [6]:
# code comes here
meatdf = df.loc[df["food_category"].isin(["Pork", "Poultry", "Fish", "Lamb & Goat", "Beef"])] #loc for rows in food category. Is in "all the meat products"
print(meatdf.co2_emmission.sum())#sum for the total

74441.13


# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [8]:
# code comes here
nonmeatdf = df.loc[~df["food_category"].isin(["Pork", "Poultry", "Fish", "Lamb & Goat", "Beef"])] # ~ to cancel out isin
print(nonmeatdf.co2_emmission.sum())

31927.98


## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.